version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      # is esm-only
      - dependency-name: chalk
        versions: '>= 5'
    cooldown:
      # update-package-lock workflow handles minor/patch updates - delay for a few weeks to give time to handle breaking change in those PRs
      default-days: 25
      semver-major-days: 5
